# Generated by Django 5.2.5 on 2025-11-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customermodel_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermodel",
            name="email",
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
