# Generated by Django 5.2.5 on 2025-11-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_remove_invoice_quotation_invoice_gst_applied_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "motor_type",
                    models.CharField(
                        choices=[
                            ("Single Phase", "Single Phase"),
                            ("Three Phase", "Three Phase"),
                            ("Submersible Single", "Submersible (Single Phase)"),
                            ("Submersible Three", "Submersible (Three Phase)"),
                        ],
                        default="Single Phase",
                        max_length=20,
                    ),
                ),
                ("power_rating", models.CharField(max_length=50)),
                ("voltage", models.CharField(max_length=50)),
                (
                    "winding_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("coil_count", models.CharField(blank=True, max_length=50, null=True)),
                ("wire_gauge", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pitch_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "turns_per_coil",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("winding_data", models.JSONField(blank=True, default=list, null=True)),
                ("rewinding_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
